### ISSUE TITLE
Client will not exit

### ISSUE THREAD

**Issue by reeyon** [aliakseis/LIII#15]
Edition	Windows 10 Pro
Version	20H2
Installed on	‎18/‎12/‎2020
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

Client version: 0.1.1.8

Problem:
After downloading/seeding for something about 10mins more or less.
The program unable to exit gracefully nor kill explicitly by ending task. 
![image](https://user-images.githubusercontent.com/3666089/116172020-83708d80-a73c-11eb-9fc9-33f01035f470.png)

Probably this is similar issue same with qbittorrent. https://github.com/qbittorrent/qBittorrent/issues/13581
To solve the *stuck* process, is to force restart the computer.

**Comment by aliakseis** [comment]
Hi,

Sorry about that. I've never experienced such behavior.

First, most probably it is not the case - but let me mention that LIII continues running when the window is closed. It is closed by either invoking Menu > File > Exit or Exit from the systray LIII icon menu.

I would recommend you to use Sysinternals Process Explorer to close irresponsive applications. At least it manages this better than Windows Task Manager:
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
Another thing: Process Explorer allows to view application thread stacks through right click > properties > threads > stacks. Also it has a possibility to create application dumps - which may help diagnosing.

Also there is turned off by default logging functionality in LIII. You can turn it on by setting in the registry:
HKEY_CURRENT_USER\SOFTWARE\LIII\LIII  > LoggingEnabled REG_SZ true

**Comment by reeyon** [comment]
Hi, to reproduce my problem, i usually stopped the torrent, exit the program by pressing the shortcut key "Alt + X" or go to File > Exit.

Attached here the process screenshot for LIII.exe
![image](https://user-images.githubusercontent.com/3666089/116196853-926c3580-a766-11eb-9b0f-2e053e898eef.png)

the Stack:
![image](https://user-images.githubusercontent.com/3666089/116196923-a9128c80-a766-11eb-9c6f-b8455e022ee0.png)

Totally have no idea what does that mean. Then I right click the process and Kill Process Tree. Then left this thread running and unable to open the Stack windows.
![image](https://user-images.githubusercontent.com/3666089/116198185-3efae700-a768-11eb-9b55-76a59bd4b883.png)

**Comment by aliakseis** [comment]
Just in case, could you please create an irresponsive app's dump as well? From the righ click menu on the app in the Proc Exp.

**Comment by aliakseis** [comment]
Another thing that can help you with diagnosing both LIII and qbittorrent is setting up App Verifier to monitor the executable:
https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier
Though it comes with SDK, it is a standalone application by itself.

**Comment by aliakseis** [comment]
Considering Proc Exp stack traces functionality - sorry I found out that at least in my case it handles 64 bits apps much better, so probably to get better results you would need to use standalone 64 bits LIII binaries (they are 100% config compatible) and probably put this pdb file unzipped next to LIII.exe:

[LIII.zip](https://github.com/aliakseis/LIII/files/6383060/LIII.zip)

**Comment by reeyon** [comment]
Hi, I put the pdb file along side with LIII.exe but problem is still persists. I have created the minidump from ProcEx if you wanna take a look [here](https://www.dropbox.com/s/9dp2u98fn9r4hvn/LIII.dmp?dl=0).

**Comment by aliakseis** [comment]
On the first sight it looks similar to https://github.com/arvidn/libtorrent/issues/314

**Comment by reeyon** [comment]
Which libtorrent version was LIII built on? Will later version resolve this issue? I see most recent versions are 1.2.13 and 2.0.3.

**Comment by aliakseis** [comment]
It is suspicious that the issue #314 went through the stale state rather than fixed.
There are issues with libtorrent updating, I am going to build with the latest boost revision for now.

Another thing - I still hope that the MS App Verifier can help to spot the issue.

**Comment by reeyon** [comment]
Hi, managed to run Application Verifier and caught some errors. Hope this is helpful for you.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<avrf:logfile xmlns:avrf="Application Verifier">
	<avrf:logSession TimeStarted="2021-04-27 : 23:29:49" PID="14708" Version="2">
		<avrf:logEntry Time="2021-04-27 : 23:29:51" LayerName="Networking" StopCode="0xE107" Severity="Error">
			<avrf:message>A Winsock API was called before a successful WSAStartup() or after a balancing successful WSACleanup() call was made</avrf:message>
			<avrf:parameter1>0 - Last sucessfull WSAStartup call by this caller. Use dps to dump the stack if not NULL</avrf:parameter1>
			<avrf:parameter2>0 - Last sucessfull WSACleanup call by this caller. Use dps to dump the stack if not NULL</avrf:parameter2>
			<avrf:parameter3>1ffdd0835b0 - Last successful WSAStartup call in this process. Use dps to dump the stack if not NULL</avrf:parameter3>
			<avrf:parameter4>0 - Last sucessfull WSACleanup call in this process. Use dps to dump the stack if not NULL</avrf:parameter4>
			<avrf:stackTrace>
				<avrf:trace>vfnet!+7ffe97dc1584 ( @ 0)</avrf:trace>
				<avrf:trace>vfnet!+7ffe97dc8238 ( @ 0)</avrf:trace>
				<avrf:trace>WSOCK32!setsockopt+61 ( @ 0)</avrf:trace>
				<avrf:trace>LIII!libtorrent::broadcast_socket::open_multicast_socket+e9 (c:\solutions\liii\src\3rdparty\torrent-rasterbar\src\broadcast_socket.cpp @ 289)</avrf:trace>
				<avrf:trace>LIII!libtorrent::broadcast_socket::open+134 (c:\solutions\liii\src\3rdparty\torrent-rasterbar\src\broadcast_socket.cpp @ 247)</avrf:trace>
				<avrf:trace>LIII!libtorrent::upnp::start+198 (c:\solutions\liii\src\3rdparty\torrent-rasterbar\src\upnp.cpp @ 137)</avrf:trace>
				<avrf:trace>LIII!libtorrent::aux::session_impl::start_upnp+289 (c:\solutions\liii\src\3rdparty\torrent-rasterbar\src\session_impl.cpp @ 6805)</avrf:trace>
				<avrf:trace>LIII!libtorrent::aux::session_impl::init+221 (c:\solutions\liii\src\3rdparty\torrent-rasterbar\src\session_impl.cpp @ 601)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::completion_handler&lt;boost::_bi::bind_t&lt;void,boost::_mfi::mf0&lt;void,libtorrent::aux::session_impl&gt;,boost::_bi::list1&lt;boost::_bi::value&lt;libtorrent::aux::session_impl *&gt; &gt; &gt; &gt;::do_complete+6b (c:\boost_1_71_0\boost\asio\detail\completion_handler.hpp @ 70)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_iocp_io_context::do_one+380 (c:\boost_1_71_0\boost\asio\detail\impl\win_iocp_io_context.ipp @ 460)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_iocp_io_context::run+da (c:\boost_1_71_0\boost\asio\detail\impl\win_iocp_io_context.ipp @ 202)</avrf:trace>
				<avrf:trace>LIII!boost::asio::io_context::run+2b (c:\boost_1_71_0\boost\asio\impl\io_context.ipp @ 64)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_thread_function+2f (c:\boost_1_71_0\boost\asio\detail\impl\win_thread.ipp @ 127)</avrf:trace>
				<avrf:trace>ucrtbase!configthreadlocale+92 ( @ 0)</avrf:trace>
				<avrf:trace>vfbasics!+7ffe97eb6a74 ( @ 0)</avrf:trace>
				<avrf:trace>KERNEL32!BaseThreadInitThunk+14 ( @ 0)</avrf:trace>
				<avrf:trace>ntdll!RtlUserThreadStart+21 ( @ 0)</avrf:trace>
			</avrf:stackTrace>
		</avrf:logEntry>
		<avrf:logEntry Time="2021-04-27 : 23:31:27" LayerName="Networking" StopCode="0xE101" Severity="Error">
			<avrf:message>Attempt to use a closed SOCKET</avrf:message>
			<avrf:parameter1>11c - SOCKET being accessed</avrf:parameter1>
			<avrf:parameter2>1ffdda7fec0 - Stack trace of the function that closed the SOCKET. Use dps to dump the stack trace if not NULL</avrf:parameter2>
			<avrf:parameter3>0 - Not used</avrf:parameter3>
			<avrf:parameter4>0 - Not used</avrf:parameter4>
			<avrf:stackTrace>
				<avrf:trace>vfnet!+7ffe97dc345f ( @ 0)</avrf:trace>
				<avrf:trace>vfnet!+7ffe97dce676 ( @ 0)</avrf:trace>
				<avrf:trace>vfnet!+7ffe97dc8245 ( @ 0)</avrf:trace>
				<avrf:trace>WSOCK32!setsockopt+61 ( @ 0)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::socket_ops::complete_iocp_connect+ad (c:\boost_1_71_0\boost\asio\detail\impl\socket_ops.ipp @ 551)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_iocp_socket_connect_op&lt;boost::_bi::bind_t&lt;void,boost::_mfi::mf1&lt;void,libtorrent::peer_connection,boost::system::error_code const &amp;&gt;,boost::_bi::list2&lt;boost::_bi::value&lt;boost::shared_ptr&lt;libtorrent::peer_connection&gt; &gt;,boost::a (c:\boost_1_71_0\boost\asio\detail\win_iocp_socket_connect_op.hpp @ 92)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_iocp_io_context::do_one+380 (c:\boost_1_71_0\boost\asio\detail\impl\win_iocp_io_context.ipp @ 460)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_iocp_io_context::run+da (c:\boost_1_71_0\boost\asio\detail\impl\win_iocp_io_context.ipp @ 202)</avrf:trace>
				<avrf:trace>LIII!boost::asio::io_context::run+2b (c:\boost_1_71_0\boost\asio\impl\io_context.ipp @ 64)</avrf:trace>
				<avrf:trace>LIII!boost::asio::detail::win_thread_function+2f (c:\boost_1_71_0\boost\asio\detail\impl\win_thread.ipp @ 127)</avrf:trace>
				<avrf:trace>ucrtbase!configthreadlocale+92 ( @ 0)</avrf:trace>
				<avrf:trace>vfbasics!+7ffe97eb6a74 ( @ 0)</avrf:trace>
				<avrf:trace>KERNEL32!BaseThreadInitThunk+14 ( @ 0)</avrf:trace>
				<avrf:trace>ntdll!RtlUserThreadStart+21 ( @ 0)</avrf:trace>
			</avrf:stackTrace>
		</avrf:logEntry>
	</avrf:logSession>
</avrf:logfile>
```

Another problem which I think is the *exit* problem. This output from WinDbg. Likely stuck at saving torrents process when quitting the program.

```shell

Microsoft (R) Windows Debugger Version 10.0.19041.685 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: "C:\Program Files (x86)\LIII BitTorrent Client\LIII.exe"

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`121a0000 00007ff7`12957000   LIII.exe
ModLoad: 00007fff`21550000 00007fff`21745000   ntdll.dll
ModLoad: 00007ffe`eb380000 00007ffe`eb3f4000   C:\WINDOWS\System32\verifier.dll
Page heap: pid 0x2990: page heap enabled with flags 0x3.
AVRF: LIII.exe: pid 0x2990: flags 0x81643027: application verifier enabled
ModLoad: 00007fff`11ec0000 00007fff`11eff000   C:\WINDOWS\SYSTEM32\vrfcore.dll
ModLoad: 00007ffe`eb400000 00007ffe`eb474000   C:\WINDOWS\SYSTEM32\vfbasics.dll
ModLoad: 00007fff`20130000 00007fff`201ed000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007fff`1f1d0000 00007fff`1f498000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007fff`18550000 00007fff`185e0000   C:\WINDOWS\SYSTEM32\apphelp.dll
ModLoad: 00007fff`21060000 00007fff`210cb000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007fff`1fa20000 00007fff`1fb4b000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007fff`1f6b0000 00007fff`1f850000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007fff`1f0a0000 00007fff`1f0c2000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007fff`1fc10000 00007fff`1fc3a000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007fff`1ed30000 00007fff`1ee3b000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007fff`1ec90000 00007fff`1ed2d000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007fff`1efa0000 00007fff`1f0a0000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007fff`20580000 00007fff`20cc2000   C:\WINDOWS\System32\SHELL32.dll
ModLoad: 00007fff`202d0000 00007fff`203fa000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007fff`211b0000 00007fff`21505000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007fff`210d0000 00007fff`2119d000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007fff`20f00000 00007fff`20fac000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007fff`1f5b0000 00007fff`1f64e000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007fff`20e60000 00007fff`20efb000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffe`c34d0000 00007ffe`c361a000   C:\Program Files (x86)\LIII BitTorrent Client\Qt5Network.dll
ModLoad: 00007fff`1ee40000 00007fff`1ef9f000   C:\WINDOWS\System32\CRYPT32.dll
ModLoad: 00007fff`00760000 00007fff`00769000   C:\WINDOWS\SYSTEM32\WSOCK32.dll
ModLoad: 00007fff`1e090000 00007fff`1e0cb000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffe`c2f10000 00007ffe`c34cc000   C:\Program Files (x86)\LIII BitTorrent Client\Qt5Core.dll
ModLoad: 00007ffe`c29b0000 00007ffe`c2f05000   C:\Program Files (x86)\LIII BitTorrent Client\Qt5Widgets.dll
ModLoad: 00007ffe`c2910000 00007ffe`c29ab000   C:\Program Files (x86)\LIII BitTorrent Client\MSVCP140.dll
ModLoad: 00007ffe`c22d0000 00007ffe`c290b000   C:\Program Files (x86)\LIII BitTorrent Client\Qt5Gui.dll
ModLoad: 00007ffe`c5ba0000 00007ffe`c5bb5000   C:\Program Files (x86)\LIII BitTorrent Client\VCRUNTIME140.dll
ModLoad: 00007fff`1e0d0000 00007fff`1e19c000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007fff`04a60000 00007fff`04a7d000   C:\WINDOWS\SYSTEM32\MPR.dll
ModLoad: 00007fff`10860000 00007fff`10878000   C:\WINDOWS\SYSTEM32\NETAPI32.dll
ModLoad: 00007fff`1eb50000 00007fff`1eb7e000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007fff`10b60000 00007fff`10b6a000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007fff`06e40000 00007fff`06e67000   C:\WINDOWS\SYSTEM32\WINMM.dll
ModLoad: 00007fff`1c5d0000 00007fff`1c5ff000   C:\WINDOWS\SYSTEM32\dwmapi.dll
ModLoad: 00007fff`1c400000 00007fff`1c49e000   C:\WINDOWS\SYSTEM32\UxTheme.dll
ModLoad: 00007fff`1e1a0000 00007fff`1e1ac000   C:\WINDOWS\SYSTEM32\NETUTILS.DLL
ModLoad: 00007ffe`fa120000 00007ffe`fa148000   C:\WINDOWS\SYSTEM32\SRVCLI.DLL
ModLoad: 00007fff`1e5f0000 00007fff`1e5fc000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffe`c1f50000 00007ffe`c1ffb000   C:\Program Files (x86)\LIII BitTorrent Client\libssl-1_1-x64.dll
ModLoad: 00007ffe`c2000000 00007ffe`c22c4000   C:\Program Files (x86)\LIII BitTorrent Client\libcrypto-1_1-x64.dll
ModLoad: 00007fff`1f4a0000 00007fff`1f4c7000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007fff`1e400000 00007fff`1e46a000   C:\WINDOWS\SYSTEM32\MSWSOCK.DLL
(2990.183c): Break instruction exception - code 80000003 (first chance)
ntdll!LdrpDoDebuggerBreak+0x30:
00007fff`21620670 cc              int     3
0:000> g
ModLoad: 00007fff`202a0000 00007fff`202d0000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007fff`20e50000 00007fff`20e58000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00007fff`201f0000 00007fff`2029e000   C:\WINDOWS\System32\shcore.dll
ModLoad: 00007fff`1cda0000 00007fff`1d531000   C:\WINDOWS\SYSTEM32\windows.storage.dll
ModLoad: 00007fff`1e690000 00007fff`1e6bc000   C:\WINDOWS\SYSTEM32\Wldp.dll
ModLoad: 00007fff`1f650000 00007fff`1f6a5000   C:\WINDOWS\System32\shlwapi.dll
ModLoad: 00007fff`1ebd0000 00007fff`1ebef000   C:\WINDOWS\SYSTEM32\profapi.dll
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
ModLoad: 00007ffe`c52c0000 00007ffe`c542e000   C:\Program Files (x86)\LIII BitTorrent Client\platforms\qwindows.dll
ModLoad: 00007fff`185e0000 00007fff`185f4000   C:\WINDOWS\SYSTEM32\WTSAPI32.dll
ModLoad: 00007fff`1d550000 00007fff`1d562000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
ModLoad: 00007fff`1f4d0000 00007fff`1f550000   C:\WINDOWS\System32\bcryptPrimitives.dll
ModLoad: 00007ffe`c6a90000 00007ffe`c6ab6000   C:\Program Files (x86)\LIII BitTorrent Client\styles\qwindowsvistastyle.dll
void __cdecl Application::checkSpecialCmdLine(void)  found args  ("C:\\Program Files (x86)\\LIII BitTorrent Client\\LIII.exe")
Starting LIII BitTorrent Client version 0.1.1.8 built Apr 25 2021 11:57:33
utilities::DeleteFileWithWaiting  deleting file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\modelState.xml-"
ModLoad: 00007fff`12200000 00007fff`1220a000   C:\Windows\System32\rasadhlp.dll
ModLoad: 00007fff`15a00000 00007fff`15a17000   C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
ModLoad: 00007fff`159e0000 00007fff`159fd000   C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
TorrentManager::addTorrent  adding file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\torrents\\3200d5130c5de82ffef18e632ea0dad056c59ff8.torrent"
ModLoad: 00007fff`16060000 00007fff`160df000   C:\WINDOWS\System32\fwpuclnt.dll
Successfully loaded fast resume data for  "3200d5130c5de82ffef18e632ea0dad056c59ff8"
TorrentManager::addTorrent  adding file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\torrents\\2e7cdd36fc74a01bee2cac20b57020c1beb8febc.torrent"
Successfully loaded fast resume data for  "2e7cdd36fc74a01bee2cac20b57020c1beb8febc"
TorrentManager::addTorrent  adding file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\torrents\\d8f48475af46d2e01af13fb5126f06f962be215c.torrent"
Successfully loaded fast resume data for  "d8f48475af46d2e01af13fb5126f06f962be215c"
ModLoad: 00007ffe`e1570000 00007ffe`e157e000   C:\Program Files (x86)\LIII BitTorrent Client\imageformats\qico.dll
ModLoad: 00007ffe`deb40000 00007ffe`deb4d000   C:\Program Files (x86)\LIII BitTorrent Client\imageformats\qgif.dll
ModLoad: 00007ffe`c1e60000 00007ffe`c1eca000   C:\Program Files (x86)\LIII BitTorrent Client\imageformats\qjpeg.dll
ModLoad: 00007fff`20cd0000 00007fff`20de5000   C:\WINDOWS\System32\MSCTF.dll
ModLoad: 00007fff`08980000 00007fff`08bff000   C:\WINDOWS\system32\dwrite.dll
ModLoad: 00007ffe`c1c90000 00007ffe`c1e5e000   C:\WINDOWS\system32\d3d9.dll
ModLoad: 00007ffe`c1b20000 00007ffe`c1c85000   C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_997a69017605b77c\igdumdim64.dll
ModLoad: 00007ffe`bd3a0000 00007ffe`c1b20000   C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_997a69017605b77c\igd9dxva64.dll
ModLoad: 00007fff`1fc40000 00007fff`200a9000   C:\WINDOWS\System32\SETUPAPI.dll
ModLoad: 00007fff`1f0d0000 00007fff`1f11e000   C:\WINDOWS\System32\cfgmgr32.dll
ModLoad: 00007fff`0ea10000 00007fff`0ec68000   C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_997a69017605b77c\igdgmm64.dll
ModLoad: 00007fff`20fb0000 00007fff`21059000   C:\WINDOWS\System32\clbcatq.dll
ModLoad: 00007ffe`ea680000 00007ffe`ea6be000   C:\WINDOWS\system32\dataexchange.dll
ModLoad: 00007fff`177e0000 00007fff`17a44000   C:\WINDOWS\system32\d3d11.dll
ModLoad: 00007fff`17a50000 00007fff`17c35000   C:\WINDOWS\system32\dcomp.dll
ModLoad: 00007fff`1d690000 00007fff`1d783000   C:\WINDOWS\system32\dxgi.dll
ModLoad: 00007fff`13560000 00007fff`13761000   C:\WINDOWS\system32\twinapi.appcore.dll
ModLoad: 00007fff`0aac0000 00007fff`0abb9000   C:\WINDOWS\SYSTEM32\textinputframework.dll
ModLoad: 00007fff`17fc0000 00007fff`1831e000   C:\WINDOWS\System32\CoreUIComponents.dll
ModLoad: 00007fff`18320000 00007fff`18412000   C:\WINDOWS\System32\CoreMessaging.dll
ModLoad: 00007fff`1d8f0000 00007fff`1d923000   C:\WINDOWS\SYSTEM32\ntmarta.dll
ModLoad: 00007fff`16960000 00007fff`16ab4000   C:\WINDOWS\SYSTEM32\wintypes.dll
ModLoad: 0000025e`16df0000 0000025e`16f44000   C:\WINDOWS\SYSTEM32\wintypes.dll
ModLoad: 00007fff`1d5f0000 00007fff`1d690000   C:\Windows\System32\FirewallAPI.dll
ModLoad: 00007fff`1d5c0000 00007fff`1d5ef000   C:\Windows\System32\fwbase.dll
ModLoad: 00007fff`07070000 00007fff`070b1000   C:\Windows\System32\FWPolicyIOMgr.dll
ModLoad: 00007ffe`e9390000 00007ffe`e95b1000   C:\WINDOWS\system32\explorerframe.dll
TorrentManager::resumeTorrent resuming: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
TorrentManager::resumeTorrent resuming: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
TorrentManager::resumeTorrent resuming: ubuntu-18.04.5-live-server-amd64.iso
Saving fastresume data for  "ubuntu-18.04.5-live-server-amd64.iso"
Saving fastresume data for  "Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]"
Saving fastresume data for  "Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]"
Fast resume data successfully saved: ubuntu-18.04.5-live-server-amd64.iso
Fast resume data successfully saved: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
Fast resume data successfully saved: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
Saving fastresume data for  "ubuntu-18.04.5-live-server-amd64.iso"
Saving fastresume data for  "Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]"
Fast resume data successfully saved: ubuntu-18.04.5-live-server-amd64.iso
Saving fastresume data for  "Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]"
Fast resume data successfully saved: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
Fast resume data successfully saved: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
Saving fastresume data for  "ubuntu-18.04.5-live-server-amd64.iso"
Saving fastresume data for  "Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]"
Saving fastresume data for  "Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]"
Fast resume data successfully saved: ubuntu-18.04.5-live-server-amd64.iso
Fast resume data successfully saved: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
Fast resume data successfully saved: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
TorrentManager::on_pauseTaskWithID pausing: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
TorrentManager::on_pauseTaskWithID pausing: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
TorrentManager::on_pauseTaskWithID pausing: ubuntu-18.04.5-live-server-amd64.iso
MainWindow::prepareToExit
void __cdecl DownloadManager::prepareToExit(void)
Saving fastresume data for  "ubuntu-18.04.5-live-server-amd64.iso"
Saving fastresume data for  "Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]"
Saving fastresume data for  "Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]"
DownloadCollectionModel::saveToFile
```

**Comment by aliakseis** [comment]
Hi, there is a new build using Boost 1.76

Considering app exit - briefly for now, I fixed app logs a bit.

These Application Verifier errors look suspicious.

**Comment by reeyon** [comment]
Good Morning, running your latest 64 build, but the process still hanging like the previous when exiting.

<details>
<summary>WinDbg output</summary>

```shell

Microsoft (R) Windows Debugger Version 10.0.19041.685 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

CommandLine: C:\Users\limruennshiang\Documents\LIII\bin\LIII.exe

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff6`c20f0000 00007ff6`c28a8000   LIII.exe
ModLoad: 00007fff`f6990000 00007fff`f6b85000   ntdll.dll
ModLoad: 00007fff`9bae0000 00007fff`9bb54000   C:\WINDOWS\System32\verifier.dll
Page heap: pid 0x95C: page heap enabled with flags 0x3.
AVRF: LIII.exe: pid 0x95C: flags 0x81643267: application verifier enabled
ModLoad: 00007fff`9bbe0000 00007fff`9bc1f000   C:\WINDOWS\SYSTEM32\vrfcore.dll
ModLoad: 00007fff`9bb60000 00007fff`9bbd4000   C:\WINDOWS\SYSTEM32\vfbasics.dll
ModLoad: 00007fff`c36c0000 00007fff`c36d1000   C:\WINDOWS\SYSTEM32\vfcompat.dll
ModLoad: 00007fff`f5990000 00007fff`f5a4d000   C:\WINDOWS\System32\KERNEL32.dll
ModLoad: 00007fff`f4510000 00007fff`f47d8000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007fff`f5380000 00007fff`f5520000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007fff`f4990000 00007fff`f49b2000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007fff`f49f0000 00007fff`f4a1a000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007fff`f4400000 00007fff`f450b000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007fff`f40d0000 00007fff`f416d000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007fff`f41f0000 00007fff`f42f0000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007fff`9ba90000 00007fff`9bada000   C:\WINDOWS\SYSTEM32\vfluapriv.dll
ModLoad: 00007fff`f52d0000 00007fff`f537c000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007fff`f5550000 00007fff`f55ee000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007fff`f5020000 00007fff`f50bb000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007fff`f6820000 00007fff`f694b000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007fff`f67b0000 00007fff`f67b8000   C:\WINDOWS\System32\psapi.dll
ModLoad: 00007fff`eb130000 00007fff`eb13a000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007fff`9ba20000 00007fff`9ba8e000   C:\WINDOWS\SYSTEM32\vfprint.dll
ModLoad: 00007fff`c3480000 00007fff`c349d000   C:\WINDOWS\SYSTEM32\vfnet.dll
ModLoad: 00007fff`d9d70000 00007fff`d9d7c000   C:\WINDOWS\SYSTEM32\vfntlmless.dll
ModLoad: 00007fff`9ba00000 00007fff`9ba20000   C:\WINDOWS\SYSTEM32\vfnws.dll
ModLoad: 00007fff`9b060000 00007fff`9b699000   C:\WINDOWS\SYSTEM32\vfcuzz.dll
ModLoad: 00007fff`f5520000 00007fff`f5550000   C:\WINDOWS\System32\IMM32.DLL
LuaPriv: Attaching to process...
-- LuaPriv initialized--
failed to set heap information 00000057
ModLoad: 00007fff`f1730000 00007fff`f17c0000   C:\WINDOWS\SYSTEM32\apphelp.dll
ModLoad: 00007fff`f2d30000 00007fff`f2d63000   C:\WINDOWS\SYSTEM32\ntmarta.dll
ModLoad: 00007fff`f50c0000 00007fff`f512b000   C:\WINDOWS\System32\WS2_32.dll
ModLoad: 00007fff`f5d00000 00007fff`f6442000   C:\WINDOWS\System32\SHELL32.dll
ModLoad: 00007fff`f4a80000 00007fff`f4baa000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007fff`f6450000 00007fff`f67a5000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007fff`f58b0000 00007fff`f597d000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007fff`98af0000 00007fff`98c3a000   C:\Users\limruennshiang\Documents\LIII\bin\Qt5Network.dll
ModLoad: 00007fff`f47e0000 00007fff`f493f000   C:\WINDOWS\System32\CRYPT32.dll
ModLoad: 00007fff`dfb40000 00007fff`dfb49000   C:\WINDOWS\SYSTEM32\WSOCK32.dll
ModLoad: 00007fff`95580000 00007fff`95b3c000   C:\Users\limruennshiang\Documents\LIII\bin\Qt5Core.dll
ModLoad: 00007fff`f34d0000 00007fff`f350b000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007fff`94f40000 00007fff`9557b000   C:\Users\limruennshiang\Documents\LIII\bin\Qt5Gui.dll
ModLoad: 00007fff`98a50000 00007fff`98aeb000   C:\Users\limruennshiang\Documents\LIII\bin\MSVCP140.dll
ModLoad: 00007fff`98a30000 00007fff`98a45000   C:\Users\limruennshiang\Documents\LIII\bin\VCRUNTIME140.dll
ModLoad: 00007fff`f3510000 00007fff`f35dc000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
ModLoad: 00007fff`949e0000 00007fff`94f35000   C:\Users\limruennshiang\Documents\LIII\bin\Qt5Widgets.dll
ModLoad: 00007fff`db690000 00007fff`db6ad000   C:\WINDOWS\SYSTEM32\MPR.dll
ModLoad: 00007fff`ea610000 00007fff`ea628000   C:\WINDOWS\SYSTEM32\NETAPI32.dll
ModLoad: 00007fff`ddbc0000 00007fff`ddbe7000   C:\WINDOWS\SYSTEM32\WINMM.dll
ModLoad: 00007fff`f3fd0000 00007fff`f3ffe000   C:\WINDOWS\SYSTEM32\USERENV.dll
ModLoad: 00007fff`f1b40000 00007fff`f1bde000   C:\WINDOWS\SYSTEM32\UxTheme.dll
ModLoad: 00007fff`f1d10000 00007fff`f1d3f000   C:\WINDOWS\SYSTEM32\dwmapi.dll
ModLoad: 00007fff`f35e0000 00007fff`f35ec000   C:\WINDOWS\SYSTEM32\NETUTILS.DLL
ModLoad: 00007fff`ce3c0000 00007fff`ce3e8000   C:\WINDOWS\SYSTEM32\SRVCLI.DLL
ModLoad: 00007fff`f3a30000 00007fff`f3a3c000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007fff`98760000 00007fff`98a24000   C:\Users\limruennshiang\Documents\LIII\bin\libcrypto-1_1-x64.dll
ModLoad: 00007fff`986b0000 00007fff`9875b000   C:\Users\limruennshiang\Documents\LIII\bin\libssl-1_1-x64.dll
ModLoad: 00007fff`f49c0000 00007fff`f49e7000   C:\WINDOWS\System32\bcrypt.dll
ModLoad: 00007fff`f3840000 00007fff`f38aa000   C:\WINDOWS\SYSTEM32\MSWSOCK.DLL
ModLoad: 00007fff`eb1d0000 00007fff`eb1e9000   C:\WINDOWS\SYSTEM32\SAMCLI.DLL
(95c.2f9c): Break instruction exception - code 80000003 (first chance)
ntdll!LdrpDoDebuggerBreak+0x30:
00007fff`f6a60670 cc              int     3
0:000> g
ModLoad: 00007fff`f5c40000 00007fff`f5c48000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00007fff`f55f0000 00007fff`f569e000   C:\WINDOWS\System32\shcore.dll
ModLoad: 00007fff`f2200000 00007fff`f2991000   C:\WINDOWS\SYSTEM32\windows.storage.dll
ModLoad: 00007fff`f3ad0000 00007fff`f3afc000   C:\WINDOWS\SYSTEM32\Wldp.dll
ModLoad: 00007fff`f4a20000 00007fff`f4a75000   C:\WINDOWS\System32\shlwapi.dll
ModLoad: 00007fff`f4010000 00007fff`f402f000   C:\WINDOWS\SYSTEM32\profapi.dll
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
ModLoad: 00007fff`947f0000 00007fff`9495e000   C:\Users\limruennshiang\Documents\LIII\bin\platforms\qwindows.dll
ModLoad: 00007fff`f17c0000 00007fff`f17d4000   C:\WINDOWS\SYSTEM32\WTSAPI32.dll
ModLoad: 00007fff`f2000000 00007fff`f2012000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
ModLoad: 00007fff`f4170000 00007fff`f41f0000   C:\WINDOWS\System32\bcryptPrimitives.dll
ModLoad: 00007fff`947c0000 00007fff`947e6000   C:\Users\limruennshiang\Documents\LIII\bin\styles\qwindowsvistastyle.dll
void __cdecl Application::checkSpecialCmdLine(void)  found args  ("C:\\Users\\limruennshiang\\Documents\\LIII\\bin\\LIII.exe")
Starting LIII BitTorrent Client version 0.1.1.9 built Apr 27 2021 18:49:04
utilities::DeleteFileWithWaiting  deleting file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\modelState.xml-"
ModLoad: 00007fff`eec20000 00007fff`eec37000   C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
ModLoad: 00007fff`eeb90000 00007fff`eebad000   C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL


=======================================
VERIFIER STOP 000000000000E107: pid 0x95C: A Winsock API was called before a successful WSAStartup() or after a balancing successful WSACleanup() call was made 

	0000000000000000 : Last sucessfull WSAStartup call by this caller. Use dps to dump the stack if not NULL
	0000000000000000 : Last sucessfull WSACleanup call by this caller. Use dps to dump the stack if not NULL
	00000230113D35B0 : Last successful WSAStartup call in this process. Use dps to dump the stack if not NULL
	0000000000000000 : Last sucessfull WSACleanup call in this process. Use dps to dump the stack if not NULL


=======================================
This verifier stop is continuable.
After debugging it use `go' to continue.

=======================================

(95c.411c): Break instruction exception - code 80000003 (first chance)
vrfcore!VerifierStopMessageEx+0x806:
00007fff`9bbe26e6 cc              int     3
0:005> g
ModLoad: 00007fff`eb6a0000 00007fff`eb6aa000   C:\Windows\System32\rasadhlp.dll
ModLoad: 00007fff`eece0000 00007fff`eed5f000   C:\WINDOWS\System32\fwpuclnt.dll
TorrentManager::addTorrent  adding file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\torrents\\3200d5130c5de82ffef18e632ea0dad056c59ff8.torrent"
Successfully loaded fast resume data for  "3200d5130c5de82ffef18e632ea0dad056c59ff8"
TorrentManager::addTorrent  adding file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\torrents\\2e7cdd36fc74a01bee2cac20b57020c1beb8febc.torrent"
Successfully loaded fast resume data for  "2e7cdd36fc74a01bee2cac20b57020c1beb8febc"
TorrentManager::addTorrent  adding file:  "C:/Users/limruennshiang/AppData/Local/LIII/LIII\\torrents\\d8f48475af46d2e01af13fb5126f06f962be215c.torrent"
Successfully loaded fast resume data for  "d8f48475af46d2e01af13fb5126f06f962be215c"
ModLoad: 00007fff`c44e0000 00007fff`c44ee000   C:\Users\limruennshiang\Documents\LIII\bin\imageformats\qico.dll
ModLoad: 00007fff`c44d0000 00007fff`c44dd000   C:\Users\limruennshiang\Documents\LIII\bin\imageformats\qgif.dll
ModLoad: 00007fff`aeb80000 00007fff`aebea000   C:\Users\limruennshiang\Documents\LIII\bin\imageformats\qjpeg.dll
ModLoad: 00007fff`f51b0000 00007fff`f52c5000   C:\WINDOWS\System32\MSCTF.dll
ModLoad: 00007fff`dad50000 00007fff`dafcf000   C:\WINDOWS\system32\dwrite.dll
ModLoad: 00007fff`ae9b0000 00007fff`aeb7e000   C:\WINDOWS\system32\d3d9.dll
ModLoad: 00007fff`ae840000 00007fff`ae9a5000   C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_997a69017605b77c\igdumdim64.dll
ModLoad: 00007fff`8f080000 00007fff`93800000   C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_997a69017605b77c\igd9dxva64.dll
ModLoad: 00007fff`f4bb0000 00007fff`f5019000   C:\WINDOWS\System32\SETUPAPI.dll
ModLoad: 00007fff`f4940000 00007fff`f498e000   C:\WINDOWS\System32\cfgmgr32.dll
ModLoad: 00007fff`e8050000 00007fff`e82a8000   C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_997a69017605b77c\igdgmm64.dll
ModLoad: 00007fff`f5c50000 00007fff`f5cf9000   C:\WINDOWS\System32\clbcatq.dll
ModLoad: 00007fff`bc060000 00007fff`bc09e000   C:\WINDOWS\system32\dataexchange.dll
ModLoad: 00007fff`eff30000 00007fff`f0194000   C:\WINDOWS\system32\d3d11.dll
ModLoad: 00007fff`f0770000 00007fff`f0955000   C:\WINDOWS\system32\dcomp.dll
ModLoad: 00007fff`f2ad0000 00007fff`f2bc3000   C:\WINDOWS\system32\dxgi.dll
ModLoad: 00007fff`ec7e0000 00007fff`ec9e1000   C:\WINDOWS\system32\twinapi.appcore.dll
ModLoad: 00007fff`dfd30000 00007fff`dfe29000   C:\WINDOWS\SYSTEM32\textinputframework.dll
ModLoad: 00007fff`f0960000 00007fff`f0cbe000   C:\WINDOWS\System32\CoreUIComponents.dll
ModLoad: 00007fff`f1140000 00007fff`f1232000   C:\WINDOWS\System32\CoreMessaging.dll
ModLoad: 00007fff`ef970000 00007fff`efac4000   C:\WINDOWS\SYSTEM32\wintypes.dll
ModLoad: 00000230`6ec10000 00000230`6ed64000   C:\WINDOWS\SYSTEM32\wintypes.dll
ModLoad: 00000230`6ed70000 00000230`6eec4000   C:\WINDOWS\SYSTEM32\wintypes.dll
ModLoad: 00007fff`f2a30000 00007fff`f2ad0000   C:\Windows\System32\FirewallAPI.dll
ModLoad: 00007fff`f2a00000 00007fff`f2a2f000   C:\Windows\System32\fwbase.dll
ModLoad: 00007fff`df080000 00007fff`df0c1000   C:\Windows\System32\FWPolicyIOMgr.dll
ModLoad: 00007fff`ba710000 00007fff`ba931000   C:\WINDOWS\system32\explorerframe.dll
TorrentManager::resumeTorrent resuming: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
TorrentManager::resumeTorrent resuming: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
TorrentManager::resumeTorrent resuming: ubuntu-18.04.5-live-server-amd64.iso
ModLoad: 00007fff`db120000 00007fff`db3ba000   C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_ca00b6081b84eb1d\comctl32.dll
ModLoad: 00007fff`ec340000 00007fff`ec4f4000   C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
ModLoad: 00007fff`bb890000 00007fff`bb8f6000   C:\Windows\System32\thumbcache.dll
ModLoad: 00007fff`ef560000 00007fff`ef600000   C:\WINDOWS\SYSTEM32\policymanager.dll
ModLoad: 00007fff`f3210000 00007fff`f329a000   C:\WINDOWS\SYSTEM32\msvcp110_win.dll
Scheduling fastresume data save for  "ubuntu-18.04.5-live-server-amd64.iso"
Scheduling fastresume data save for  "Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]"
Scheduling fastresume data save for  "Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]"
Saving fastresume data for  ubuntu-18.04.5-live-server-amd64.iso
Fast resume data successfully saved: ubuntu-18.04.5-live-server-amd64.iso
Saving fastresume data for  Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
Fast resume data successfully saved: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
Saving fastresume data for  Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
Fast resume data successfully saved: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
TorrentManager::on_pauseTaskWithID pausing: Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]
TorrentManager::on_pauseTaskWithID pausing: Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]
TorrentManager::on_pauseTaskWithID pausing: ubuntu-18.04.5-live-server-amd64.iso
MainWindow::prepareToExit
void __cdecl DownloadManager::prepareToExit(void)
Scheduling fastresume data save for  "ubuntu-18.04.5-live-server-amd64.iso"
Scheduling fastresume data save for  "Justice.Society.World.War.II.2021.720p.WEBRip.800MB.x264-GalaxyRG[TGx]"
Scheduling fastresume data save for  "Mortal Kombat (2021) [720p] [WEBRip] [YTS.MX]"
DownloadCollectionModel::saveToFile
```
</details>

**Comment by aliakseis** [comment]
Hi,

I've attempted to address the issue here.
Could you please try it?

[bin-x64.zip](https://github.com/aliakseis/LIII/files/6390098/bin-x64.zip)

**Comment by reeyon** [comment]
> Hi,
> 
> I've attempted to address the issue here.
> Could you please try it?
> 
> [bin-x64.zip](https://github.com/aliakseis/LIII/files/6390098/bin-x64.zip)

Hi, tried. No improvement. Its still happening randomly.
Since this is only happening to me, if that's the case, let me close the issue.
I must say this client is giving _Very Good_ speed. Especially _Seeding_.
I can live with that issue that I'm having right now. Thank you.

**Comment by aliakseis** [comment]
Thank you! -
https://www.youtube.com/watch?v=xRhxJHj37xE

**Comment by reeyon** [comment]
Hi @aliakseis , just an update for my issue. It seems problem has been resolved by removing obsolete/unsupported driver from my machine.
Occasionally, my machine will occur BSOD from time to time (_Kernel Security Check Failure error_) , which I thought it was Windows 10 issues itself or the hardware driver causes this.

Since I have installed WinDbg on my machine while troubleshooting LIII, I've also installed [BluescreenView](https://www.nirsoft.net/utils/blue_screen_view.html) to scan the minidumps to see why there was BSODs occurred randomly.
Turns out it was due to one of the driver resides in ```%windir%\system32\drivers``` was causing this BSOD. I removed it yesterday and monitoring, if no BSOD again then its good news for me. This custom driver was developed by a company for private VPN usage, and it is very outdated (like XP/Win7 time) and the ex-developers had abandoned the project. 

For LIII, so far tested with random open and exit couple of times, it did exit properly now. 

My apologies for the inconvenience that caused to you.
Thank you.

**Comment by smaragdus** [comment]
llllpq) Fri Apr 30 05:19:30 GMT+03:00 2021 aliakseis/LIII ***@***.***>: Hi @aliakseis , just an update for my issue. It seems problem has been resolved by removing obsolete/unsupported driver from my machine. Occasionally, my machine will occur BSOD from time to time (Kernel Security Check Failure error) , which I thought it was Windows 10 issues itself or the hardware driver causes this. Since I have installed WinDbg on my machine while troubleshooting LIII, I've also installed BluescreenView to scan the minidumps to see why there was BSODs occurred randomly. Turns out it was due to one of the driver resides in %windir%\system32\drivers was causing this BSOD. I removed it yesterday and monitoring, if no BSOD again then its good news for me. This custom driver was developed by a company for private VPN usage, and it is very outdated (like XP/Win7 time) and the ex-developers had abandoned the project. For LIII, so far tested with random open and exit couple of times, it did exit properly now. My apologies for the inconvenience that caused to you. Thank you. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aliakseis** [comment]
Thank you!
